//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayerWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackArtists
    {
        public int ID { get; set; }
        public int TrackID { get; set; }
        public int ArtistID { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Tracks Tracks { get; set; }
    }
}
