//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayerWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracks()
        {
            this.TrackArtists = new HashSet<TrackArtists>();
        }
    
        public int TrackID { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
        public int AlbumID { get; set; }
    
        public virtual Albums Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackArtists> TrackArtists { get; set; }
    }
}
